version: 2.1
orbs:
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: henryeff/javaproject
          tag: 1.0.1
      - docker/push:
          image: henryeff/javaproject
          tag: 1.0.1
  deploy:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a javaproject5
            heroku container:release web -a javaproject5
  scan:
    docker:
      - image: cimg/openjdk:19.0.1
    environment:
      IMAGE_NAME: henryeff/javaproject
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME
          severity-threshold: "high"

workflows:
  simple_workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - develop
                - release
      - scan:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - release
                - develop
      - publish:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - release
      - deploy:
          requires:
            - publish
          filters:
            branches:
              only:
                - release
